### ISSUE TITLE
[Bug] Update removed functions for Python 3.12

### ISSUE THREAD

**Issue by ZashIn** [Kezyma/ModOrganizer-Plugins#36]
ModOrganizer 2.5.2 switched to Python 3.12, which removed some deprecated functions, including `Path.link_to()`, which has been [deprecated since Python 3.10](https://docs.python.org/3.11/library/pathlib.html#pathlib.Path.link_to).
So hard links are probably not working anymore in MO 2.5.2.

So `Path.link_to()` has to be replaced by `Path.hardlink_to()`.

**Comment by ZashIn** [comment]
So all your plugins are supposed to be compatible with both MO 2.4 and 2.5? So targeting Python 3.8, 3.11 and 3.12?
That would mean adding compatibility wrappers for deprecated functions from 3.11 and 3.12. Not sure if anything else besides `Path.link_to()` is effected.

For the patch in [common_utilities.py](https://github.com/Kezyma/ModOrganizer-Plugins/blob/0974c0c6d28f4051aea45423d0fe777ec8ba56b9/src/common/common_utilities.py):
- What is the reason for the retries on all file operations in [common_utilities.py](https://github.com/Kezyma/ModOrganizer-Plugins/blob/0974c0c6d28f4051aea45423d0fe777ec8ba56b9/src/common/common_utilities.py)?
- I recommend to only catch OS related file operations (`OSError`). Using plain excepts makes it much harder to find a bug like this, preventing any such file operation to ever work - especially considering the retries.

**Comment by Kezyma** [comment]
The retries in there were added in an attempt to fix some of the issues with profile sync randomly breaking and then never getting triggered again, but due to the inconsistency of the bug it's almost impossible to figure out if it's helped or not.

I was going to try and implement some kind of queue system to handle file operations for it, but limited time and the complexity of figuring it out meant that I simply haven't gotten around to it.
